/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.guy_sw.versioning.server;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

  public static void main(String[] args) {
    System.out.println("Welcome To Versioning Project Weather Server!");
    SpringApplication.run(App.class, args);
  }
}
