/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.guy_sw.versioning.server;

public class App {

  public static void main(String[] args) {
    System.out.println("Welcome To Versioning Project Weather Server!");
  }
}
